language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk7

sudo: false

cache:
  directories:
    - $HOME/.ivy2/
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions/

env:
  matrix:
    - SPARK_VERSION=1.6.0 SPARK_BUILD="spark-1.6.0-bin-hadoop2.6" SPARK_BUILD_URL="http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz"

before_install:
 - ./bin/download_travis_dependencies.sh

script:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  - sbt -Dspark.version=$SPARK_VERSION "set test in assembly := {}" assembly
  #- sbt -Dspark.version=$SPARK_VERSION test
